### ISSUE TITLE
Download data as txt file

### ISSUE THREAD

**Issue by SteveGoldstein** [carlbfrederick/ohiCovidMetrics#15]
This feature request might belong in some other repo.

The "Download" widget on the [web site](https://www.dhs.wisconsin.gov/covid-19/local.htm) only allows for images.  It would be great to have the data available as a text, csv, or excel file.   Even better would be to have a complete table with the Activity  Level calls for every day for every region and county.

**Comment by carlbfrederick** [comment]
Closing @SteveGoldstein you can now download the data as a text file using the download link
