### ISSUE TITLE
test_cum is wrong because hdt$NEGATIVE is a factor

### ISSUE THREAD

**Issue by SteveGoldstein** [carlbfrederick/ohiCovidMetrics#16]
The test_cum values do not match the POSITIVE+NEGATIVE values in the data from the
[dashboard](https://data.dhsgis.wi.gov/datasets/covid-19-historical-data-table/data?where=GEO%20%3D%20%27State%27)
Here's the [download link](https://opendata.arcgis.com/datasets/b913e9591eae4912b33dc5b4e88646c5_10.csv).

This can be fixed by setting `stringsAsFactors=FALSE` in the `st_read()` call on line 63 in `R/data_pull_fcns.R`:
` hdt <- sf::st_set_geometry(sf::st_read(api_url, quiet = TRUE,stringsAsFactors=FALSE), NULL)`

**Comment by carlbfrederick** [comment]
Thanks!  Same with TEST_NEW.  Must have broken when I stopped downloading the statewide numbers.  The next commit will fix the issue.
