### ISSUE TITLE
producing-confirmed-case-mertics.Rmd: data frame hdt_out has Trajectory as character rather than numeric

### ISSUE THREAD

**Issue by klittle314** [carlbfrederick/ohiCovidMetrics#23]
this Rmd appears to be internal document but I flag this issue in case you use the function process_confirmed_cases in production.  

At line 99 in the chunk _metrics-all_ that creates the data frame hdt_out, the function _process_confirmed_cases_ applied to hdt_clean yields hdt_out$Trajectory as character.   

This leads to an error in the comparison chunk _import-jeff_

To get the file to run, I just forced the type change, 
`hdt_out$Trajectory <- as.numeric(hdt_out$Trajectory)`

**Comment by carlbfrederick** [comment]
Yes ... I introduced this error to fit our Tableau load specs and need to fix the comparisons down below.
