### ISSUE TITLE
use one-sided alternatives in the rev cusum procedure

### ISSUE THREAD

**Issue by klittle314** [carlbfrederick/ohiCovidMetrics#25]
**Reverse cusum logic notes: discussion of alternative hypothesis in test procedure**
(this may not be a 'real issue' if the reverse cusum procedure will not be part of regular review.)

The reverse cusum procedure identifies an upper or lower limit with stats::poisson.test(x=c(curr,cum_lim),T=c(1,delta_t)). 

The default alternative hypothesis is ‘two-sided’.

Here’s the argument for one-sided alternatives in the limit calculations instead.

Upper limit: For each delta_t in counting weeks backwards from the current week, the procedure increases cum_lim by one until the value is ‘too large’ according to the poisson.test. The null hypothesis states the ratio of the current value curr to cum_lim value equals 1. As cum_lim by construction is always larger than curr, the procedure examines ratios that are strictly decreasing.  The ratio cannot be larger than 1, so the alternative hypothesis should be defined as ‘less than’.

Lower limit: For each delta_t in counting weeks backwards from the current week, the procedure decreases cum_lim by one until the value is ‘too small’ according to the poisson test; the procedure stops if the cum_lim drops below zero. The null hypothesis states the ratio of the current value curr to cum_lim value equals 1. As cum_lim by construction is always smaller than curr, the procedure examines ratios that are strictly increasing. The ratio cannot be smaller than 1, the alternative hypothesis should be definedas ‘greater than’.

Examples are provided in the document Chart_notes_KL.Rmd for Wisconsin, Dane County, and Iron County cases thru 17 June.   The impact of changing to use one-sided alternative hypotheses in the examples is relatively small, with the limits being slightly tighter in the examples I studied.

Recommend:  the function calls to poisson.test need changing in the UCL function, similarly for the LCL function.  E.g.:

```#Revision of functions by Carl Friedrick to specify one-sided alternative
rev_cusum_uclA <- function(curr, delta_t) {
  # requires: non-negative integer count, curr,  and positive integer weight, delta_t
  curr <- check_nonneg(curr, "curr")
  delta_t <- check_nonneg(delta_t, "delta_t")

  if (delta_t == 0L) {
    return(NA_real_)
  }

  # effects: returns the smallest count greater than curr that would provide significance 
  # at 3-sigma probability
  cum_lim <- delta_t * curr + 1
  p <- stats::poisson.test( c( curr , cum_lim ) , T = c( 1 , delta_t ), alt = 'l' )$p.value
  while( p > stats::pnorm(-3) ) {
    cum_lim <- cum_lim + 1
    p <- stats::poisson.test( c( curr , cum_lim ) , T = c( 1 , delta_t ), alt = 'l'  )$p.value
  }

  out <- cum_lim/delta_t - curr

  out
}

**Comment by carlbfrederick** [comment]
waiting til after metric calculation functions are correct since we are not using these functions at the moment.

**Comment by carlbfrederick** [comment]
these functions have been deprecated as of bb790a205c9ab2d6f77a727277bd3bec551299a2
